import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { assertExecutionAuthorization } from "../../extension/conductor-ownership.mjs";

export const BEGIN = "<!-- CONDUCTOR:STATE:BEGIN -->";
export const END = "<!-- CONDUCTOR:STATE:END -->";
export const TRANSITIONS = new Map([
  ["idle", ["map-done"]], ["map-done", ["plan-done"]], ["plan-done", ["build-done"]],
  ["build-done", ["verify-done"]], ["verify-done", ["complete"]], ["complete", []],
]);

export function digest(value) { return crypto.createHash("sha256").update(value).digest("hex"); }

export function parseStateText(text) {
  const start = text.indexOf(BEGIN); const end = text.indexOf(END);
  if (start < 0 || end < 0 || end <= start || text.indexOf(BEGIN, start + BEGIN.length) >= 0 || text.indexOf(END, end + END.length) >= 0) throw new Error("state must contain exactly one ordered marker pair");
  const body = text.slice(start + BEGIN.length, end).trim();
  const match = body.match(/^```json\s*\n([\s\S]*?)\n```$/);
  if (!match) throw new Error("state marker body must be one fenced json block");
  let state; try { state = JSON.parse(match[1]); } catch (error) { throw new Error(`invalid state JSON: ${error.message}`); }
  return { state, prefix: text.slice(0, start), suffix: text.slice(end + END.length) };
}

export function formatStateText(parts, state) {
  const active = Object.entries(state.sections || {}).filter(([, section]) => section.status === "in-progress").map(([id]) => id).sort();
  const projection = `\n\n## Human projection (generated by coordinator)\n\n- Run: ${state.run.id || "not started"}\n- Status: ${state.run.status}\n- Revision: ${state.revision}\n- Map: ${state.map.sha256 || "not validated"}\n- Active sections: ${active.join(", ") || "none"}\n- Mechanical verification: ${state.verification.mechanical.status}\n- Review: ${state.verification.review.status}\n- Telemetry: ${state.telemetry.status}\n`;
  return `${parts.prefix}${BEGIN}\n\u0060\u0060\u0060json\n${JSON.stringify(state, null, 2)}\n\u0060\u0060\u0060\n${END}${projection}`;
}

const STATUS_ORDER = ["idle", "map-done", "plan-done", "build-done", "verify-done", "complete"];
const ACCEPTED_WRITER_STATUSES = new Set(["checked", "verified"]);

function latestAttempt(section) { return Array.isArray(section.attempts) ? section.attempts.at(-1) : undefined; }

export function validateState(state) {
  const errors = [];
  if (!state || typeof state !== "object" || Array.isArray(state)) return ["state must be an object"];
  if (state.schemaVersion !== 2) errors.push("schemaVersion must be 2");
  if (typeof state.conductorVersion !== "string" || !state.conductorVersion) errors.push("conductorVersion is required");
  if (!Number.isSafeInteger(state.revision) || state.revision < 0) errors.push("revision must be a non-negative integer");
  if (!state.run || typeof state.run !== "object") errors.push("run is required");
  else {
    if (typeof state.run.id !== "string") errors.push("run.id must be a string");
    if (!TRANSITIONS.has(state.run.status)) errors.push(`invalid run.status '${state.run.status}'`);
    if (state.run.status !== "idle" && (!state.run.id || !state.run.task || !Number.isFinite(Date.parse(state.run.startedAt)))) errors.push("non-idle run requires id, task, and startedAt");
    if (!["pending", "accepted", "rejected", "needs-human-review", "failed"].includes(state.run.outcome)) errors.push("invalid run.outcome");
  }
  if (!state.map || typeof state.map.path !== "string") errors.push("map.path is required");
  else if (state.run?.status !== "idle" && (!/^[a-f0-9]{64}$/.test(state.map.sha256 || "") || !Number.isFinite(Date.parse(state.map.validatedAt)))) errors.push("non-idle run requires validated map digest/timestamp");
  if (!Array.isArray(state.contracts)) errors.push("contracts must be an array");
  if (!state.sections || typeof state.sections !== "object" || Array.isArray(state.sections)) errors.push("sections must be an object");
  else for (const [id, section] of Object.entries(state.sections)) {
    if (!section || typeof section !== "object") { errors.push(`section '${id}' must be an object`); continue; }
    if (!["pending", "in-progress", "done", "blocked", "failed", "skipped"].includes(section.status)) errors.push(`section '${id}' has invalid status`);
    if (!Array.isArray(section.dependsOn)) errors.push(`section '${id}' dependsOn must be an array`);
    const wo = section.workOrder;
    if (!wo || typeof wo !== "object") errors.push(`section '${id}' workOrder is required`);
    else {
      for (const key of ["contracts", "do", "doneWhen", "declaredFiles", "deliverables", "commands"]) if (!Array.isArray(wo[key])) errors.push(`section '${id}' workOrder.${key} must be an array`);
      const reportTemplate = `.conductor/runs/<run>/agents/${section.agent}/<pi-run>/events.jsonl`;
      if (!(wo.deliverables || []).some((item) => item?.kind === "checkpoint-jsonl" && item.pathTemplate === reportTemplate)) errors.push(`section '${id}' requires checkpoint deliverable '${reportTemplate}'`);
      for (const declared of wo.declaredFiles || []) if (typeof declared !== "string" || !declared || declared.startsWith("/") || /^[A-Za-z]:[\\/]/.test(declared) || declared.replaceAll("\\", "/").split("/").includes("..") || /[*?[]/.test(declared)) errors.push(`section '${id}' declaredFiles must contain exact safe repository paths`);
      for (const command of wo.commands || []) {
        if (!command.id || !Array.isArray(command.argv) || !command.argv.length || command.argv.some((x) => typeof x !== "string")) errors.push(`section '${id}' has invalid shell-free command`);
        if (!Number.isSafeInteger(command.timeoutMs) || command.timeoutMs <= 0 || command.timeoutMs > 600000) errors.push(`section '${id}' command '${command.id || "unknown"}' timeoutMs must be 1..600000`);
      }
      for (const key of ["exploreMs", "buildMs", "verifyMs", "graceMs", "heartbeatMs"]) if (!Number.isSafeInteger(wo.budgets?.[key]) || wo.budgets[key] <= 0) errors.push(`section '${id}' workOrder.budgets.${key} must be positive`);
    }
    if (!Array.isArray(section.attempts)) errors.push(`section '${id}' attempts must be an array`);
    else for (const [attemptIndex, attempt] of section.attempts.entries()) {
      if (!attempt || typeof attempt !== "object") { errors.push(`section '${id}' attempt ${attemptIndex + 1} must be an object`); continue; }
      if (attempt.piRunId !== undefined && !/^[A-Za-z0-9._-]+$/.test(attempt.piRunId)) errors.push(`section '${id}' attempt ${attemptIndex + 1} has unsafe piRunId`);
      if (attempt.reportPath !== undefined && (typeof attempt.reportPath !== "string" || !attempt.reportPath)) errors.push(`section '${id}' attempt ${attemptIndex + 1} has invalid reportPath`);
      if (attempt.acceptance !== undefined && (!attempt.acceptance || !["pending", "claimed", "review-required", "checked", "verified", "rejected"].includes(attempt.acceptance.status))) errors.push(`section '${id}' attempt ${attemptIndex + 1} has invalid acceptance status`);
      if (attempt.checks !== undefined && (!Array.isArray(attempt.checks) || attempt.checks.some((check) => !check?.id || !["passed", "failed", "skipped"].includes(check.status)))) errors.push(`section '${id}' attempt ${attemptIndex + 1} has invalid checks`);
    }
    if (section.resolvedEvents !== undefined && (!Array.isArray(section.resolvedEvents) || section.resolvedEvents.some((value) => typeof value !== "string"))) errors.push(`section '${id}' resolvedEvents must be a string array`);
    if (section.status === "done") {
      const attempt = latestAttempt(section);
      if (!attempt?.piRunId || !attempt.reportPath || !ACCEPTED_WRITER_STATUSES.has(attempt.acceptance?.status)) errors.push(`done section '${id}' requires a latest identity-bound report and checked/verified acceptance`);
      const requiredCommands = (section.workOrder?.commands || []).filter((command) => command.required !== false);
      for (const command of requiredCommands) if (!attempt?.checks?.some((check) => check.id === command.id && check.status === "passed")) errors.push(`done section '${id}' is missing passed declared check '${command.id}'`);
    }
  }
  if (state.scheduling !== undefined && (state.scheduling?.mode !== "ready" || !Number.isSafeInteger(state.scheduling.maxConcurrency) || state.scheduling.maxConcurrency < 1 || state.scheduling.maxConcurrency > 32)) errors.push("scheduling requires mode ready and maxConcurrency 1..32");
  if (state.scheduling?.mode === "ready") { try { const waves = taskWaves(state.sections); if (JSON.stringify(waves) !== JSON.stringify(state.waves)) errors.push("waves must be the deterministic task DAG projection"); } catch (error) { errors.push(error.message); } }
  if (!Array.isArray(state.waves)) errors.push("waves must be an array");
  if (!state.verification || typeof state.verification !== "object") errors.push("verification is required");
  else {
    if (!["pending", "passed", "failed"].includes(state.verification.mechanical?.status) || !Array.isArray(state.verification.mechanical?.checks)) errors.push("invalid mechanical verification");
    if (!["pending", "accepted", "rejected", "infra-failure", "infra-closed"].includes(state.verification.review?.status)) errors.push("invalid review status");
    if (!["pending", "accepted", "rejected", "needs-human-review"].includes(state.verification.verdict)) errors.push("invalid verification verdict");
  }
  if (!state.telemetry || !["pending", "appended", "failed"].includes(state.telemetry.status)) errors.push("invalid telemetry status");
  const statusIndex = STATUS_ORDER.indexOf(state.run?.status);
  if (statusIndex >= STATUS_ORDER.indexOf("plan-done") && (!Object.keys(state.sections || {}).length || !state.waves.length)) errors.push("plan-done and later require non-empty sections and waves");
  if (statusIndex >= STATUS_ORDER.indexOf("build-done") && Object.values(state.sections || {}).some((section) => !["done", "skipped"].includes(section.status))) errors.push("build-done and later require all sections done or skipped");
  if (statusIndex >= STATUS_ORDER.indexOf("verify-done")) {
    if (state.verification?.mechanical?.status !== "passed" || state.verification?.mechanical?.checks?.some((check) => check.required !== false && check.status !== "passed")) errors.push("verify-done and later require all required mechanical checks passed");
    if (state.verification?.review?.status !== "accepted" || state.verification?.verdict !== "accepted") errors.push("verify-done and later require accepted review/verdict");
  }
  if (state.run?.status === "complete" && (state.telemetry?.status !== "appended" || state.run.outcome !== "accepted" || !state.report)) errors.push("complete requires appended telemetry, accepted outcome, and final report");
  return errors;
}

export function readState(file) {
  const text = fs.readFileSync(file, "utf8"); const parsed = parseStateText(text); const errors = validateState(parsed.state);
  if (errors.length) throw new Error(`state validation failed: ${errors.join("; ")}`);
  return { ...parsed, text, digest: digest(text) };
}

function merge(target, patch) {
  if (!patch || typeof patch !== "object" || Array.isArray(patch)) return patch;
  const result = { ...(target || {}) };
  for (const [key, value] of Object.entries(patch)) result[key] = value && typeof value === "object" && !Array.isArray(value) ? merge(result[key], value) : value;
  return result;
}

function fsyncDirectory(directory) { let fd; try { fd = fs.openSync(directory, "r"); fs.fsyncSync(fd); } finally { if (fd !== undefined) fs.closeSync(fd); } }

export function atomicWrite(file, content, options = {}) {
  const directory = path.dirname(file); fs.mkdirSync(directory, { recursive: true });
  const temp = path.join(directory, `.${path.basename(file)}.${process.pid}.${crypto.randomBytes(4).toString("hex")}.tmp`);
  let fd;
  try {
    fd = fs.openSync(temp, "wx", 0o600); fs.writeFileSync(fd, content); fs.fsyncSync(fd); fs.closeSync(fd); fd = undefined;
    if (options.beforeRename) options.beforeRename(temp);
    fs.renameSync(temp, file); fsyncDirectory(directory);
  } catch (error) { if (fd !== undefined) fs.closeSync(fd); try { fs.unlinkSync(temp); } catch {} throw error; }
}

export function prospectiveState(current, patch = {}, toStatus) {
  if (!patch || typeof patch !== "object" || Array.isArray(patch)) throw new Error("state patch must be an object");
  for (const key of ["schemaVersion", "conductorVersion", "revision"]) if (Object.hasOwn(patch, key)) throw new Error(`state patch may not change protected field '${key}'`);
  if (patch.run && Object.hasOwn(patch.run, "status")) throw new Error("state patch may not change run.status; use state transition");
  let next = merge(current, patch); if (toStatus) next = merge(next, { run: { status: toStatus } }); next.revision = current.revision + 1; return next;
}

export function mutateState(file, options = {}) {
  const ownerFile = path.join(path.dirname(file), ".conductor", "engine.lock");
  if (fs.existsSync(ownerFile)) { const owner = JSON.parse(fs.readFileSync(ownerFile, "utf8")); if (options.ownerToken !== owner.token) throw new Error("state is locked by engine coordinator"); }
  const lock = `${file}.lock`; const fd = fs.openSync(lock, "wx", 0o600);
  try { return mutateStateUnlocked(file, options); } finally { fs.closeSync(fd); fs.unlinkSync(lock); }
}

function mutateStateUnlocked(file, { expectedRevision, expectedStatus, patch = {}, toStatus, beforeRename } = {}) {
  if (!Number.isSafeInteger(expectedRevision)) throw new Error("--expected-revision is required");
  if (!expectedStatus) throw new Error("--expected-status is required");
  const current = readState(file);
  if (current.state.revision !== expectedRevision) throw new Error(`revision conflict: expected ${expectedRevision}, found ${current.state.revision}`);
  if (current.state.run.status !== expectedStatus) throw new Error(`status conflict: expected ${expectedStatus}, found ${current.state.run.status}`);
  if (toStatus && toStatus !== expectedStatus && !(TRANSITIONS.get(expectedStatus) || []).includes(toStatus)) throw new Error(`illegal transition ${expectedStatus} -> ${toStatus}`);
  const next = prospectiveState(current.state, patch, toStatus);
  const errors = validateState(next); if (errors.length) throw new Error(`next state invalid: ${errors.join("; ")}`);
  const comparableCurrent = { ...current.state, revision: next.revision };
  if (JSON.stringify(comparableCurrent) === JSON.stringify(next)) throw new Error("zero-change state mutation refused");
  const output = formatStateText(current, next); atomicWrite(file, output, { beforeRename });
  const reread = readState(file);
  if (reread.state.revision !== next.revision || reread.state.run.status !== next.run.status || reread.digest !== digest(output)) throw new Error("state write postcondition failed");
  return reread;
}

export function validateActiveAgreement(state, active) {
  const errors = [];
  if (!active || active.schemaVersion !== 1) return ["active.schemaVersion must be 1"];
  if (active.runId !== state.run.id) errors.push("active.runId does not match state.run.id");
  if (active.authorization !== "snapshot" && active.stateRevision !== state.revision) errors.push("active.stateRevision does not match state.revision");
  if (active.authorization !== "snapshot" && !state.waves.some((wave) => wave.id === active.waveId)) errors.push("active.waveId is not in state.waves");
  if (!["build", "verify", "repair", "map"].includes(active.phase)) errors.push("active.phase is invalid");
  if (!Array.isArray(active.executions) || !active.executions.length) errors.push("active.executions must be non-empty");
  for (const execution of active.executions || []) {
    if (active.authorization === "snapshot") { try { assertExecutionAuthorization(state, active, execution); } catch (error) { errors.push(error.message); } }
    if (execution.piRunId !== undefined && !/^[A-Za-z0-9._-]+$/.test(execution.piRunId)) errors.push(`active piRunId for '${execution.section}' is unsafe`);
    if (active.phase === "map") {
      if (execution.agent !== "cartographer" || execution.section !== "cartographer") errors.push("map phase may only authorize the cartographer");
      continue;
    }
    const section = state.sections[execution.section];
    if (!section) errors.push(`active section '${execution.section}' is unknown`);
    else {
      if (section.status !== "in-progress") errors.push(`active section '${execution.section}' is not in-progress`);
      if (execution.agent !== section.agent) errors.push(`active agent for '${execution.section}' does not match state`);
      const expected = [...section.workOrder.declaredFiles].sort(); const actual = [...(execution.declaredFiles || [])].sort();
      if (JSON.stringify(expected) !== JSON.stringify(actual)) errors.push(`active declaredFiles for '${execution.section}' do not match state`);
      const bound = latestAttempt(section)?.piRunId;
      if (bound && execution.piRunId !== bound) errors.push(`active piRunId for '${execution.section}' does not match its bound attempt`);
    }
  }
  return errors;
}

// Atomically rebind an existing active marker to the current state revision and, once
// child run IDs are persisted in attempts, to those exact Pi run identities. This is
// the only legal way to advance active state after a mid-wave state mutation.
export function taskWaves(sections) {
  const pending = new Set(Object.keys(sections || {})), done = new Set(), waves = [];
  for (const [id, section] of Object.entries(sections || {})) {
    if (!Array.isArray(section.dependsOn) || new Set(section.dependsOn).size !== section.dependsOn.length) throw new Error(`invalid task dependencies for '${id}'`);
    for (const dep of section.dependsOn) if (!pending.has(dep)) throw new Error(`unknown task dependency '${dep}'`);
  }
  while (pending.size) { const ready = [...pending].filter(id => sections[id].dependsOn.every(dep => done.has(dep))).sort(); if (!ready.length) throw new Error("task dependency cycle"); waves.push({ id: `wave-${waves.length + 1}`, sections: ready }); for (const id of ready) { pending.delete(id); done.add(id); } }
  return waves;
}

export function refreshActiveMarker(projectRoot, { expectedRunId } = {}) {
  if (!expectedRunId) throw new Error("active refresh requires --expected-run-id");
  const activeFile = path.join(projectRoot, ".conductor", "active.json");
  if (!fs.existsSync(activeFile)) throw new Error("active.json is absent; use preflight --activate");
  const active = JSON.parse(fs.readFileSync(activeFile, "utf8"));
  const current = readState(path.join(projectRoot, ".conductor-state.md"));
  if (active.runId !== expectedRunId || current.state.run.id !== expectedRunId) throw new Error("active refresh expected run ID conflict");
  const refreshed = { ...active, stateRevision: current.state.revision, executions: active.executions.map((execution) => {
    const section = current.state.sections[execution.section];
    const bound = section?.attempts?.at(-1)?.piRunId;
    if (!bound) throw new Error(`active refresh requires a persisted Pi run ID for '${execution.section}'`);
    return { ...execution, piRunId: bound };
  }) };
  const before = validateActiveAgreement(current.state, refreshed); if (before.length) throw new Error(`refreshed active marker would be invalid: ${before.join("; ")}`);
  if (JSON.stringify(active) === JSON.stringify(refreshed)) throw new Error("zero-change active refresh refused");
  atomicWrite(activeFile, `${JSON.stringify(refreshed, null, 2)}\n`);
  const reread = JSON.parse(fs.readFileSync(activeFile, "utf8"));
  const errors = validateActiveAgreement(current.state, reread);
  if (errors.length || reread.stateRevision !== current.state.revision) throw new Error(`active refresh postcondition failed: ${errors.join("; ") || "revision not advanced"}`);
  return reread;
}
